### ISSUE TITLE
Converting trajectory filters to moveit tutorial has inappropriate links

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-attic/industrial_experimental#1]
The tutorial found here: http://ros.org/wiki/industrial_trajectory_filters/Tutorials/Converting%20arm%20navigation%20trajectory%20filters%20into%20moveit%20Planning%20Request%20Adapters

has links to the source repo.  This should be updated (post hydro) to link to doxygen documents.

**Comment by gavanderhoorn** [comment]
_inappropriate_ even? :)
