### ISSUE TITLE
CAT vehicle teleop mode error

### ISSUE THREAD

**Issue by Ayushas2427** [ros-industrial-attic/industrial_experimental#12]
I have used the tutorials of the [CAT Vehicle](http://link.removed) . i simulated the vehicle on gazebo and the vehicle performed well.

Now, i used the teleop mode to move the vehicle.
The TurtleBot teleop node is publishing Twist messages to /cmd_vel_mux/input/teleop ,and to convert them into /catvehicle/cmd_vel.

The following command is used for conversion:
_$ rosrun topic_tools relay /cmd_vel_mux/input/teleop /catvehicle/cmd_vel_

But the vehicle is not responding. May i please know where is the error?
Though,the vehicle is responding well with the "hard left turn" as shown in the [tutorial](http://link.removed).

Kindly help.
Best Regards

**Comment by gavanderhoorn** [comment]
I"m as confused as @ipa-mdl was in ros-industrial/ros_canopen#231: what does your question have to do with the packages in this repository?

**Comment by gavanderhoorn** [comment]
You've already posted this to ROS Answers ([here](http://answers.ros.org/question/258819)), then to `ros-industrial/ros_canopen` and now here, so could I ask you to not cross-post your issues to unrelated trackers/sites?

**Comment by Ayushas2427** [comment]
@gavanderhoorn , well, it seems i am unable to understand the ideal location for my question then. 
and as a newbie in this field, i expect seniors like you to help me on this.

This link you shared of my question resembles the scenario when i modified the vehicle files (launch files and the urdf) and configurations and it stopped working. In this case, i have not modified any bit of data, it rather copying and pasting of commands from official sources. So, i do not feel this is a cross question, it is rather a similar question with different configurations. 

"Closing" a file is an easy job, but helping inexperienced students (like me), is something,which will be appreciated more. 
I regret for my mistake, but the main part (of questions solving) remains unsolved.
My best Regards

**Comment by gavanderhoorn** [comment]
You've already posted this on a more suitable forum (ie: ROS Answers), so I'm left to guess why you've picked a few repositories on the `ros-industrial` organisation to post this question to as a duplicate?

But in any case: don't you think the original author of the blogpost that you link to would be the one to answer your questions? It seems strange to expect people that have no relation to the packages that you try to use to know about them and to be able to answer questions about them.

We all started out as *newbies*, but we didn't post questions to random places and expected them to be answered there.

Wouldn't you agree?

**Comment by Ayushas2427** [comment]
Sir,I respectfully agree.
I did not have an idea of how GitHub "issue" section works, and i simply posted my question without knowing the fact that one has to post questions as per the repository, and later i got confused with the ideal location, which was later corrected by you and by @ipa-mdl. So i just posted my slightly varied ques (from the link you shared before) on GitHub with the fear that my somewhat different question would be closed at the "ROS-Answers" with the tag of "duplicate" just the way you did,sir.

But, without taking this further, it is always great to learn from seniors like you. 👍  I shall keep the fact of raising questions at suitable locations in mind. It is better to approach the author instead. I regret for my mistakes.
Warm Regards
